name: Continuous Integration
on:
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        scala: [3.1.3, 2.13.10]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Build project
        run: sbt ++${{ matrix.scala }} test

  scalafmt:
    name: Scalafmt
    strategy:
      matrix:
        scala: [3.1.3, 2.13.10]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout current branch (fast)
        uses: actions/checkout@v3.0.2

      - name: Scalafmt
        run: sbt ++${{ matrix.scala }} scalafmtCheckAll
